kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
        - name: devops
          image: somilmore/phone-book  # Updated Docker image
          imagePullPolicy: Always
          ports:
            - containerPort: 8009   # Spring Boot application port (assuming it's running on 8080)
---
kind: Service
apiVersion: v1
metadata:
  name: devops-service
spec:
  selector:
    app: devops
  ports:
    - protocol: TCP
      port: 8080      # Port on which the service will be exposed
      targetPort: 8009   # Target port of the Spring Boot application
  type: LoadBalancer        # Expose the service using NodePort
